include birim/başlık/Makefile
include birim/cüzdan/Makefile
include birim/dil/Makefile
include birim/lato/Makefile
include birim/logo/Makefile
include birim/paralar/Makefile
include birim/tckt/Makefile
include birim/telefon/Makefile
