type = "javascript"
account_id = "8f0c2f2271ff857947d9a5b2c38595a0"
zone_id = "cb31764917040dd0b9a7b79e1ec099df"
compatibility_date = "2022-04-02"

name = "test"
workers_dev = true
route = ""
kv_namespaces = [
  { binding = "KV", id = "15a080fd128945ecb0a9b1780f0e708a", preview_id = "69b9fd26875141d1b832ccaa3934647a" },
]

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.beta]
name = "beta"
workers_dev = false
route = "https://beta.kimlikdao.org/*"
kv_namespaces = [
  { binding = "KV", id = "15a080fd128945ecb0a9b1780f0e708a"},
]

[build]
command = "make cf-deployment"
upload = { format = "service-worker" }
