type = "javascript"
account_id = "8f0c2f2271ff857947d9a5b2c38595a0"
zone_id = "cb31764917040dd0b9a7b79e1ec099df"
compatibility_date = "2022-04-02"

name = "test"
workers_dev = true
route = ""

[dev]
ip = "0.0.0.0"
port = 80
local_protocol = "http"

[env.fujitestnet]
name = "fujitestnet"
workers_dev = false
route = "https://fujitestnet.kimlikdao.org/*"

kv_namespaces = [
  { binding = "KV", id = "f5dd6a87ada14a288622f94019dac027" },
]

[build]
command = "make cf-deployment"
upload = { format = "service-worker" }