export default {
  multipass: true,
  plugins: [
    "cleanupAttrs",
    "cleanupEnableBackground",
    { name: "cleanupIDs", params: {"floatPrecision": 1 }},
    "cleanupNumericValues",
    "collapseGroups",
    "convertColors",
    "convertEllipseToCircle",
    "convertPathData",
    "convertShapeToPath",
    "convertTransform",
    "inlineStyles",
    "mergePaths",
    "mergeStyles",
    "minifyStyles",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    "removeComments",
    "removeDesc",
    "removeDoctype",
    "removeEditorsNSData",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "removeEmptyText",
    "removeHiddenElems",
    "removeMetadata",
    "removeNonInheritableGroupAttrs",
    "removeTitle",
    "removeUnknownsAndDefaults",
    "removeUnusedNS",
    "removeUselessDefs",
    "removeUselessStrokeAndFill",
    "removeViewBox",
    "removeXMLProcInst",
    "sortAttrs",
    "sortDefsChildren",
  ],
}
