name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  build-dapp:
    name: dApp'ı oluştur
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Repoyu al
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bun kur
        uses: oven-sh/setup-bun@v1

      - name: Araçları kur
        run: |
          bun i
          brew install pngcrush brotli zopfli woff2 webp
          pip install fonttools

      - name: ana sayfa
        run: |
          make ana.sayfa

      - name: al sayfası
        run: |
          make al.sayfa

      - name: tcktm sayfası
        run: |
          make tcktm.sayfa

      - name: iptal sayfası
        run: |
          make iptal.sayfa

      - name: oyla sayfası
        run: |
          make oyla.sayfa

      - name: sunucu
        run: |
          make build/sunucu/prod.js
