name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  build-dapp:
    name: dApp'ı oluştur
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Repoyu al
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bun kur
        uses: oven-sh/setup-bun@v2

      - name: Araçları kur
        run: |
          bun i
          brew install pngcrush brotli zopfli woff2 webp librsvg
          pip install fonttools

      - name: ana sayfa
        run: bun run build
