name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  compile-components:
    name: Compile individual pages
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Get the source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies
        run: bun i

      - name: Install brew dependencies
        run: brew install pngcrush brotli zopfli woff2 webp librsvg

      - name: Install pip dependencies
        run: pip install fonttools

      - name: Compile Landing and Mint pages
        run: bun run build --lang en

  compile-dapp:
    if: false # Temporarily disabled
    name: Compile the dApp
    runs-on: macos-latest
    steps:
      - name: Get the source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies
        run: bun i

      - name: Install brew dependencies
        run: brew install pngcrush brotli zopfli woff2 webp librsvg

      - name: Install pip dependencies
        run: pip install fonttools

      - name: Compile the dApp
        run: bun run build
