name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  build-dapp:
    name: dApp'ı oluştur
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Repoyu al
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Node kur
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Araçları kur
        run: |
          yarn
          brew install pngcrush brotli zopfli woff2
          pip install fonttools
          make ana.sayfa

      - name: ana sayfa
        run: |
          make ana.sayfa

      - name: al sayfası
        run: |
          make al.sayfa

      - name: incele sayfası
        run: |
          make incele.sayfa

      - name: iptal sayfası
        run: |
          make iptal.sayfa

      - name: oyla sayfası
        run: |
          make oyla.sayfa

      - name: sunucu
        run: |
          make build/sunucu/prod.js
