name: All tests

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  build-dapp:
    name: dApp'ı oluştur
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - name: Repoyu al
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bun kur
        uses: oven-sh/setup-bun@v2

      - name: "`cüzdan` birimini derle"
        run: bun lib/kdjs/kdjs.js birim/cüzdan/birim.js --globals '{"GEN":false,"DefaultChain":"0x1","Chains":["0x1","0xa4b1"]}'

      - name: "`dil` birimini derle"
        run: bun lib/kdjs/kdjs.js birim/dil/birim.js --globals '{"GEN":false,"Route":{"en":"mint","tr":"al"}}'

      - name: "`kpass` birimini derle"
        run: bun lib/kdjs/kdjs.js birim/kpass/birim.js --globals '{"GEN":false}'

      - name: Araçları kur
        run: |
          bun i
          brew install pngcrush brotli zopfli woff2 webp librsvg
          pip install fonttools

      - name: ana sayfa
        run: bun run build
